const pokemons = [
    { number: 1, name: "Bulbasaur", type: "Planta/Veneno" },
    { number: 2, name: "Ivysaur", type: "Planta/Veneno" },
    { number: 3, name: "Venusaur", type: "Planta/Veneno" },
    { number: 4, name: "Charmander", type: "Fuego" },
    { number: 5, name: "Charmeleon", type: "Fuego" },
    { number: 6, name: "Charizard", type: "Fuego/Volador" },
    { number: 7, name: "Squirtle", type: "Agua" },
    { number: 8, name: "Wartortle", type: "Agua" },
    { number: 9, name: "Blastoise", type: "Agua" },
    { number: 10, name: "Caterpie", type: "Bicho" },
    { number: 11, name: "Metapod", type: "Bicho" },
    { number: 12, name: "Butterfree", type: "Bicho/Volador" },
    { number: 13, name: "Weedle", type: "Bicho/Veneno" },
    { number: 14, name: "Kakuna", type: "Bicho/Veneno" },
    { number: 15, name: "Beedrill", type: "Bicho/Veneno" },
    { number: 16, name: "Pidgey", type: "Normal/Volador" },
    { number: 17, name: "Pidgeotto", type: "Normal/Volador" },
    { number: 18, name: "Pidgeot", type: "Normal/Volador" },
    { number: 19, name: "Rattata", type: "Normal" },
    { number: 20, name: "Raticate", type: "Normal" },
    { number: 21, name: "Spearow", type: "Normal/Volador" },
    { number: 22, name: "Fearow", type: "Normal/Volador" },
    { number: 23, name: "Ekans", type: "Veneno" },
    { number: 24, name: "Arbok", type: "Veneno" },
    { number: 25, name: "Pikachu", type: "Eléctrico" },
    { number: 26, name: "Raichu", type: "Eléctrico" },
    { number: 27, name: "Sandshrew", type: "Tierra" },
    { number: 28, name: "Sandslash", type: "Tierra" },
    { number: 29, name: "Nidoran♀", type: "Veneno" },
    { number: 30, name: "Nidorina", type: "Veneno" },
  ];
  